import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang='en'>
        <body>
          <div className='navbar'>
            <Link href='/'>Home</Link>
            <Link href='/list'>List</Link>
            <Link href='/cart'>Cart</Link>
          </div>
          {children}
          {/* page.js들이 props로 들어감 */}
        </body>
      </html>
    </>
  );
}
